CREATE TABLE PUBLIC.BANK_PARAMS (
	ID INTEGER NOT NULL,
	MAX_LOAN_AMOUNT NUMERIC(10,2) DEFAULT 4000.00 NOT NULL,
	BASE_INTEREST_RATE NUMERIC(10,2) DEFAULT 100.00 NOT NULL,
	INTEREST_RATE_FACTOR NUMERIC(10,1) DEFAULT 1.5 NOT NULL,
	MAX_LOAN_ATTEMPTS TINYINT DEFAULT 3 NOT NULL,
	RISK_TIME_START TIME NOT NULL,
	RISK_TIME_END TIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.CUSTOMER (
	ID INTEGER NOT NULL,
	NAME CHARACTER(25) NOT NULL,
	SURNAME CHARACTER(25) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.LOAN (
	ID INTEGER NOT NULL,
	LOAN_REQUEST_ID INTEGER NOT NULL,
	CURRENT_INTEREST_RATE NUMERIC(10,2) NOT NULL,
	CURRENT_INTEREST NUMERIC(10,2) NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.LOAN_EXTENSION (
	ID INTEGER NOT NULL,
	LOAN_ID INTEGER NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	INTEREST_RATE NUMERIC(10,2) NOT NULL,
	INTEREST NUMERIC(10,2) NOT NULL,
	SUBMISSION_DATE DATE NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.LOAN_REQUEST (
	ID INTEGER NOT NULL,
	CUSTOMER_ID INTEGER NOT NULL,
	SUBMISSION_DATE DATE NOT NULL,
	SUBMISSION_TIME TIME NOT NULL,
	TERM INTEGER NOT NULL,
	AMOUNT NUMERIC(10,2) NOT NULL,
	STATUS CHARACTER(8) DEFAULT 'NEW     ' NOT NULL,
	REQUEST_IP_ID INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.REQUEST_IP (
	ID INTEGER NOT NULL,
	IP CHARACTER(15) NOT NULL,
	LOAN_ATTEMPTS TINYINT DEFAULT 0 NOT NULL,
	LAST_LOAN_ATTEMPT DATE NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE PUBLIC.LOAN
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER (ID);



ALTER TABLE PUBLIC.LOAN_EXTENSION
	ADD FOREIGN KEY (LOAN_ID)
	REFERENCES LOAN (ID);



ALTER TABLE PUBLIC.LOAN_REQUEST
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER (ID);

ALTER TABLE PUBLIC.LOAN_REQUEST
	ADD FOREIGN KEY (REQUEST_IP_ID)
	REFERENCES REQUEST_IP (ID);



CREATE INDEX PUBLIC.SYS_IDX_10453 ON PUBLIC.LOAN (CUSTOMER_ID);

CREATE INDEX PUBLIC.SYS_IDX_10478 ON PUBLIC.LOAN_REQUEST (CUSTOMER_ID);

CREATE INDEX PUBLIC.SYS_IDX_10505 ON PUBLIC.LOAN_REQUEST (REQUEST_IP_ID);

CREATE INDEX PUBLIC.SYS_IDX_11003 ON PUBLIC.LOAN_EXTENSION (LOAN_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_CT_10256_10261 ON PUBLIC.REQUEST_IP (IP);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_CT_10323_10333 ON PUBLIC.LOAN (LOAN_REQUEST_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10104_10105 ON PUBLIC.CUSTOMER (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10143_10144 ON PUBLIC.LOAN_REQUEST (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10166_10167 ON PUBLIC.BANK_PARAMS (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10255_10257 ON PUBLIC.REQUEST_IP (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10322_10324 ON PUBLIC.LOAN (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10980_10981 ON PUBLIC.LOAN_EXTENSION (ID);
