
DROP TABLE LOAN_EXTENSION IF EXISTS CASCADE;
DROP TABLE LOAN_REQUEST IF EXISTS CASCADE;
DROP TABLE CUSTOMER  IF EXISTS CASCADE;
DROP TABLE REQUEST_IP IF EXISTS CASCADE;
DROP TABLE BANK_PARAMS IF EXISTS CASCADE;